#!/bin/bash

NPM_PATH=`which npm`
NODEGYP_PATH="node ${NPM_PATH%bin/npm}/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"

if [[ $OS == 'cygwin' ]]; then
  NODEGYP_PATH=node-gyp
fi

cp native_mate.gyp binding.gyp
"$NODEGYP_PATH" rebuild . && rm binding.gyp
